//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Resource.rc 使用
//
#define IDW_MAIN                        41
#define IDW_ABOUT                       42
#define IDW_VIEW_TOOLBAR                43
#define IDW_VIEW_STATUSBAR              44
#define IDW_READY                       45
#define IDW_INDICATOR_CAPS              46
#define IDW_INDICATOR_NUM               47
#define IDW_INDICATOR_SCRL              48
#define IDW_MENUBAR                     49
#define IDW_TOOLBAR                     50
#define IDW_QUIT                        51
#define IDW_MDI_CASCADE                 52
#define IDW_MDI_TILE                    53
#define IDW_MDI_ARRANGE                 54
#define IDW_MDI_CLOSEALL                55
#define IDW_FIRSTCHILD                  56
#define IDW_CHILD2                      57
#define IDW_CHILD3                      58
#define IDW_CHILD4                      59
#define IDW_CHILD5                      60
#define IDW_CHILD6                      61
#define IDW_CHILD7                      62
#define IDW_CHILD8                      63
#define IDW_CHILD9                      64
#define IDW_CHILD10                     65
#define IDW_FILE_MRU_FILE1              66
#define IDW_FILE_MRU_FILE2              67
#define IDW_FILE_MRU_FILE3              68
#define IDW_FILE_MRU_FILE4              69
#define IDW_FILE_MRU_FILE5              70
#define IDW_FILE_MRU_FILE6              71
#define IDW_FILE_MRU_FILE7              72
#define IDW_FILE_MRU_FILE8              73
#define IDW_FILE_MRU_FILE9              74
#define IDW_FILE_MRU_FILE10             75
#define IDW_FILE_MRU_FILE11             76
#define IDW_FILE_MRU_FILE12             77
#define IDW_FILE_MRU_FILE13             78
#define IDW_FILE_MRU_FILE14             79
#define IDW_FILE_MRU_FILE15             80
#define IDW_FILE_MRU_FILE16             81
#define IDW_SPLITH                      82
#define IDW_SPLITV                      83
#define IDW_TRACK4WAY                   84
#define IDW_SDBOTTOM                    85
#define IDW_SDCENTER                    86
#define IDW_SDLEFT                      87
#define IDW_SDMIDDLE                    88
#define IDW_SDRIGHT                     89
#define IDW_SDTOP                       90
#define IDD_DIALOG1                     121
#define IDD_DIALOG_ABOUT                121
#define IDB_TOOLBAR_NORM                122
#define IDB_TOOLBAR_HOT                 165
#define IDB_TOOLBAR_DIS                 166
#define IDT_TOOLBAR_OPEN                169
#define IDT_TOOLBAR_SAVE                170
#define IDD_DIALOG_COMMON_COMPILE_LUA   170
#define IDT_TOOLBAR_START               171
#define IDD_DIALOG_COMMON_COMPILE_TCC   171
#define IDT_TOOLBAR_STOP                172
#define IDD_DIALOG_OPTIONS              172
#define IDT_TOOLBAR_CLEAR               173
#define IDT_TOOLBAR_OPTIONS             174
#define IDT_TOOLBAR_ABOUT               175
#define IDC_FILTER_PORT                 1000
#define IDC_HOME_ADDR                   1002
#define IDC_BUTTON_COMPILE              1008
#define IDC_BUTTON_RUN                  1009
#define IDC_LISTVIEW_ADAPTER_LIST       1011
#define IDC_RADIO_PROTOCOL_ALL          1012
#define IDC_RADIO_PROTOCOL_TCP          1013
#define IDC_RADIO_PROTOCOL_UDP          1014
#define IDC_RADIO_PROTOCOL_ICMP         1015
#define IDC_RADIO_CAPTURE_METHOD_RAWSOCKET 1016
#define IDC_RADIO_CAPTURE_METHOD_WINPCAP 1017
#define IDC_RADIO_IP_ALL                1018
#define IDC_RADIO_IP_CERTAIN            1019
#define IDC_RADIO_IP_SOURCE             1019
#define IDC_FILTER_IP_ADDR              1020
#define IDC_RADIO_PORT_ALL              1021
#define IDC_RADIO_PORT_CERTAIN          1022
#define IDC_RADIO_PORT_SOURCE           1022
#define IDC_LICENCE_EDIT                1023
#define IDC_BUTTON_OPEN                 1024
#define IDC_BUTTON_SAVE                 1025
#define IDC_BUTTON_SAVEAS               1026
#define IDC_EDIT_RESULT                 1027
#define IDC_BUTTON_OK1                  1028
#define IDC_BUTTON_CANCEL1              1029
#define IDC_RADIO_IP_DEST               1030
#define IDC_RADIO_IP_BOTH               1031
#define IDC_RADIO_PORT_DEST             1032
#define IDC_RADIO_PORT_BOTH             1033
#define IDC_CHECK_VALID_DATA_LENGTH     1034
#define ID_AA_FILE                      32771
#define IDM_FILE_OPEN                   32772
#define IDM_FILE_SAVE                   32773
#define IDM_FILE_EXIT                   32774
#define IDM_CAPTURE_START               32775
#define IDM_CAPTURE_STOP                32776
#define IDM_CAPTURE_CLEAR               32777
#define IDM_VIEW_OPTIONS                32778
#define ID_OPTIONS_PLUGIN               32779
#define IDM_LUA_COMPILE_TEST            32780
#define IDM_TCC_COMPILE_TEST            32781
#define IDM_PLUGIN_REINIT               32782
#define IDM_HELP_ABOUT                  32783
#define IDM_INVALID                     32784
#define ID_ACCELERATOR32784             32785
#define ID_ACCELERATOR32785             32786
#define ID_OPTIONS_AUTOSCROLL           32787
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           160
#endif
#endif
